## Exploración de Datos

In [20]:
# Leer y combinar todos los archivos CSV y XLS de la carpeta raw en un solo DataFrame
import os
import glob

raw_dir = '../data/raw/'
file_types = ['*.csv', '*.xls', '*.xlsx']
all_files = []
for year in os.listdir(raw_dir):
    year_path = os.path.join(raw_dir, year)
    if os.path.isdir(year_path):
        for ext in file_types:
            all_files.extend(glob.glob(os.path.join(year_path, ext)))

dfs = []
for file in all_files:
    print(f'Leyendo archivo: {file}')
    if file.endswith('.csv'):
        dfs.append(pd.read_csv(file, encoding='latin1', on_bad_lines='skip'))
    elif file.endswith('.xls') or file.endswith('.xlsx'):
        dfs.append(pd.read_excel(file))

df_all = pd.concat(dfs, ignore_index=False)
print(f'Total archivos leídos: {len(all_files)}')
print(f'Tamaño del DataFrame combinado: {df_all.shape}')

Leyendo archivo: ../data/raw/2020\cbacsv_nov2020.csv
Leyendo archivo: ../data/raw/2020\cbapromsector_feb2020.csv
Leyendo archivo: ../data/raw/2020\cba_agosto2020.csv
Leyendo archivo: ../data/raw/2020\cba_dic2020.csv
Leyendo archivo: ../data/raw/2020\cba_junio2020.csv
Leyendo archivo: ../data/raw/2020\cba_mar2020.csv
Leyendo archivo: ../data/raw/2020\cba_octubre2020.csv
Leyendo archivo: ../data/raw/2020\cba_sept2020.csv
Leyendo archivo: ../data/raw/2020\cba_julio2020.xls
Leyendo archivo: ../data/raw/2021\cba_abril2021csv.csv
Leyendo archivo: ../data/raw/2021\cba_ago2021.csv
Leyendo archivo: ../data/raw/2021\cba_enero2021-csv.csv
Leyendo archivo: ../data/raw/2021\cba_febrero2021-csv.csv
Leyendo archivo: ../data/raw/2021\cba_julio2021-csv.csv
Leyendo archivo: ../data/raw/2021\cba_marzo_csv2021.csv
Leyendo archivo: ../data/raw/2021\cba_nov2021.csv
Leyendo archivo: ../data/raw/2021\cba_sept2021csv.csv
Leyendo archivo: ../data/raw/2022\cbamayo2022.csv
Leyendo archivo: ../data/raw/2022\cba_abril2022_csv.csv
Leyendo archivo: ../data/raw/2022\cba_ene2022.csv
Leyendo archivo: ../data/raw/2022\cba_feb2022.csv
Leyendo archivo: ../data/raw/2022\cba_junio2022.csv
Leyendo archivo: ../data/raw/2022\cba_marzo2022csv.csv
Total archivos leídos: 23
Tamaño del DataFrame combinado: (1371, 263)

In [ ]:
path = '2020/cba_mar2020.csv'
with open(raw_dir + path, encoding='latin1') as f:
    lines = f.readlines()[1:]  # Remueve la primera fila

from io import StringIO
df2020_3 = pd.read_csv(StringIO(''.join(lines)))
df2020_3.head()

,Unnamed: 0,Unnamed: 1,Producto,Medida,CASA DE LA CARNE CANGREJO,REY DE VIA ESPA¥A,RIBA SMITH BELLA VISTA,RIBA SMITH TRANSISTMICA,SUPER 99 CAMINO REAL,SUPER 99 EL DORADO,...,SUPER 99 LA CUCHILLA CALIDONIA,Unnamed: 74,SUPER 99 MA¥ANITAS,Unnamed: 76,EL FUERTE VILLA ZAITA,Unnamed: 78,REY MILLA 8,Unnamed: 80,SUPER 99 LA CABIMA,Unnamed: 82
0,14.0,1.0,Babilla (Carne de res de Primera) *,1 Kilogramos,6.45,6.55,6.45,6.55,6.45,6.45,...,NaN,NaN,6.55,NaN,NaN,NaN,NaN,6.55,6.45,6.55
1,14.0,2.0,Bistec de Cinta *,1 Kilogramos,4.96,5.62,5.62,5.62,5.62,5.62,...,5.62,5.62,5.62,NaN,5.17,5.17,5.62,5.50,5.54,5.50
2,14.0,3.0,Carne Molida de Primera *,1 Kilogramos,4.72,4.72,4.74,4.74,4.74,4.74,...,4.74,4.74,4.74,NaN,4.45,4.45,NaN,4.56,4.74,4.56
3,14.0,4.0,Carne para Sopa (Costilla) *,1 Kilogramos,4.64,4.64,4.64,4.64,4.45,4.64,...,NaN,NaN,4.45,NaN,NaN,NaN,NaN,4.64,4.64,4.64
4,14.0,5.0,Puerco Liso *,1 Kilogramos,5.72,6.31,14.26,14.26,4.79,6.31,...,NaN,NaN,4.79,NaN,NaN,NaN,NaN,6.09,6.31,6.09

In [ ]:
path = '2020/cba_julio2020.xls'
df2020_7 = pd.read_excel(raw_dir + path)
df2020_7.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Producto,Medida,CASA DE LA CARNE CANGREJO,REY DE VIA ESPAÑA,RIBA SMITH BELLA VISTA,RIBA SMITH TRANSISTMICA,SUPER 99 CAMINO REAL,...,ABT EDITH- SANTA ANA,MINISUPER EXPRESO-CALIDONIA,MINISUPER ROY-CALIDONIA,MINISUPER EL MILENIO,M/S VILLA ZAITA,M/S OCÉANO,ABARROTERÍA BERAKA,ABT - LA PAGODA,ABT. LA PAGODA NO. 2,M/S MULTI CARNES
0,NaN,14,1,Babilla (Carne de res de Primera) *,1 Kilogramos,NaN,6.55,NaN,6.55,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.33,6.05,6.54
1,NaN,14,2,Bistec de Cinta *,1 Kilogramos,5.6,5.62,NaN,5.62,NaN,...,5.62,NaN,NaN,NaN,NaN,NaN,NaN,5.40,NaN,5.62
2,NaN,14,3,Carne Molida de Primera *,1 Kilogramos,NaN,NaN,4.74,4.74,4.74,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,14,4,Carne para Sopa (Costilla) *,1 Kilogramos,4.7,NaN,NaN,5.85,NaN,...,NaN,NaN,NaN,5.51,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,14,5,Puerco Liso *,1 Kilogramos,7.8,NaN,14.26,11.83,NaN,...,8.27,6.28,NaN,5.51,NaN,7.17,7.17,NaN,5.17,5.62

In [24]:
path = '2020/cba_sept2020.csv'
with open(raw_dir + path, encoding='latin1') as f:
    lines = f.readlines()[2:]  # Remueve la primera fila

df2020_9 = pd.read_csv(StringIO(''.join(lines)))
df2020_9.head()

,Unnamed: 0,Unnamed: 1,CASA DE LA CARNE CANGREJO,REY DE VIA ESPAï¿½A,RIBA SMITH BELLA VISTA,RIBA SMITH TRANSISTMICA,SUPER 99 CAMINO REAL,SUPER 99 EL DORADO,SUPER 99 TUMBA MUERTO,XTRA TUMBA MUERTO,...,MINISUPER - JUAN Dï¿½AZ,MINISUPER JULY ZHANG- JUAN Dï¿½AZ,M/S SUSANA LUO JUAN DIAZ,MINISUPER PLAZA AMADOR,ABT EDITH- SANTA ANA,MINISUPER EXPRESO-CALIDONIA,MINISUPER ROY-CALIDONIA,ABT - LA PAGODA,ABT. LA PAGODA NO. 2,M/S MULTI CARNES
0,Babilla (Carne de res de Primera) *,1 Kilogramos,NaN,NaN,6.55,6.55,NaN,NaN,NaN,6.53,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.33,6.05,6.54
1,Bistec de Cinta *,1 Kilogramos,4.96,NaN,NaN,5.62,5.62,NaN,5.62,5.60,...,NaN,NaN,NaN,NaN,5.62,NaN,NaN,5.40,4.51,6.52
2,Carne Molida de Primera *,1 Kilogramos,NaN,3.75,4.74,4.74,4.74,4.74,4.74,NaN,...,4.74,NaN,NaN,NaN,NaN,NaN,NaN,5.51,4.73,3.75
3,Carne para Sopa (Costilla),1 Kilogramos,NaN,NaN,5.85,NaN,4.45,4.45,4.45,4.54,...,4.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Puerco Liso,1 Kilogramos,7.80,6.15,11.83,14.26,NaN,NaN,5.75,5.73,...,6.28,NaN,NaN,6.06,7.17,6.28,NaN,4.96,5.17,5.62

In [23]:
path = '2020/cbacsv_nov2020.csv'
with open(raw_dir + path, encoding='latin1') as f:
    lines = f.readlines()[1:]  # Remueve la primera fila

df2020_11 = pd.read_csv(StringIO(''.join(lines)), on_bad_lines='skip', delimiter=';')
df2020_11.head()

,Producto,Medida,CASA DE LA CARNE CANGREJO,REY DE VIA ESPA¥A,RIBA SMITH BELLA VISTA,RIBA SMITH TRANSISTMICA,REY EL DORADO,SUPER 99 CAMINO REAL,SUPER 99 EL DORADO,SUPER 99 TUMBA MUERTO,...,ABT EDITH- SANTA ANA,MINISUPER EXPRESO-CALIDONIA,MINISUPER ROY-CALIDONIA,MINISUPER EL MILENIO,M/S VILLA ZAITA,M/S OCANO,ABARROTERÖA BERAKA,ABT - LA PAGODA,ABT. LA PAGODA NO. 2,M/S MULTI CARNES
0,Babilla (Carne de res de Primera) *,1 Kilogramos,NaN,6.55,6.55,6.55,6.55,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.33,6.05,6.54
1,Bistec de Cinta *,1 Kilogramos,NaN,NaN,5.62,5.62,NaN,5.62,5.62,5.62,...,NaN,NaN,NaN,5.62,NaN,5.40,NaN,5.40,4.73,5.62
2,Carne Molida de Primera *,1 Kilogramos,NaN,NaN,4.74,4.74,NaN,4.74,4.74,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.39,4.73,4.41
3,Carne para Sopa (Costilla),1 Kilogramos,NaN,NaN,NaN,NaN,NaN,3.56,3.56,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.94,NaN,5.84
4,Puerco Liso,1 Kilogramos,7.8,NaN,14.26,14.26,6.83,4.99,NaN,NaN,...,5.51,NaN,NaN,5.51,NaN,7.17,NaN,5.40,6.36,5.62

In [33]:
df = pd.concat([df2020_1, df2020_2], ignore_index=True)
df.describe().round(2)

,CASA DE LA CARNE CANGREJO,REY DE VIA ESPA¥A,RIBA SMITH BELLA VISTA,RIBA SMITH TRANSISTMICA,SUPER 99 CAMINO REAL,SUPER 99 EL DORADO,SUPER 99 TUMBA MUERTO,XTRA TUMBA MUERTO,EL MACHETAZO COSTA SUR,EL MACHETAZO METRO MALL,...,MINISUPER EXPRESO-CALIDONIA,MINISUPER ROY-CALIDONIA,MINISUPER EL MILENIO,M/S VILLA ZAITA,ABARROTERÖA BERAKA,ABT - LA PAGODA,ABT. LA PAGODA NO. 2,M/S MULTI CARNES,REY EL DORADO,M/S OCANO
count,82.00,83.00,88.00,98.00,94.00,87.00,97.00,95.00,90.00,85.00,...,42.00,40.00,79.00,73.00,68.00,81.00,78.00,79.00,42.00,31.00
mean,2.69,2.43,2.87,3.16,2.48,2.28,2.62,2.26,2.55,2.61,...,1.71,1.44,2.34,2.17,1.85,2.41,2.06,2.30,2.54,1.74
std,2.37,1.99,2.61,3.18,2.22,1.93,2.40,2.23,2.39,2.42,...,1.42,1.17,1.87,1.77,1.29,2.08,1.62,1.98,2.50,1.29
min,0.50,0.35,0.45,0.45,0.35,0.35,0.35,0.27,0.39,0.40,...,0.50,0.30,0.40,0.40,0.35,0.25,0.25,0.20,0.49,0.25
25%,0.90,0.95,0.92,0.92,0.95,0.94,0.95,0.89,0.89,0.93,...,0.76,0.75,0.86,0.85,0.85,0.88,0.79,0.86,1.02,0.86
50%,1.76,1.75,1.96,2.08,1.78,1.76,1.79,1.66,1.54,1.75,...,1.12,0.97,1.54,1.54,1.34,1.96,1.48,1.60,1.88,1.25
75%,3.76,3.02,3.84,3.80,2.80,2.72,2.89,2.70,2.95,2.98,...,2.21,1.75,3.31,3.31,2.95,3.28,2.87,3.20,3.06,2.35
max,11.29,8.20,14.30,14.47,11.49,10.57,10.99,11.46,10.65,11.75,...,6.28,5.75,7.72,8.71,5.95,10.45,6.58,8.26,14.49,5.35